site_name: Camarade

repo_url: https://github.com/josekoalas/camarade
repo_name: josekoalas/camarade
edit_uri: edit/main/docs/

nav:
  - Empieza aquí:
    - index.md 
    - Entorno de desarrollo: empieza_aqui/entorno_desarrollo.md
    - Pruebas: empieza_aqui/pruebas.md
  - Asignaturas:
    - asignaturas/index.md
    - Primero:
      - asignaturas/primero/index.md
      - Programacion I: asignaturas/primero/programacion_i.md
      - Programacion II: asignaturas/primero/programacion_ii.md
    - Segundo:
      - asignaturas/segundo/index.md
    - Tercero:
      - asignaturas/tercero/index.md
    - Cuarto:
      - asignaturas/cuarto/index.md
  - Recursos:
    - recursos/index.md
    - Libros: recursos/libros.md
  - Sobre el grado:
    - grado/index.md
    - Exámenes: grado/examenes.md
    - Horarios y grupos: grado/horarios.md

theme:
  name: material
  custom_dir: overrides
  language: es
  icon:
    logo: octicons/dependabot-16
    repo: fontawesome/brands/github
  favicon: assets/images/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: amber
      toggle:
        icon: material/brightness-2
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: amber
      toggle:
        icon: material/brightness-5
        name: Cambiar a modo claro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.code.annotate
    - content.code.copy

plugins:
  - search
  - git-committers:
      repository: josekoalas/camarade
      branch: main

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets

extra_css:
  - extra/extra.css
extra_javascript:
  - extra/extra.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false